"""Añadir llave foranea

Revision ID: 220d73a354aa
Revises: d29d02d9140b
Create Date: 2025-05-16 11:25:42.039990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '220d73a354aa'
down_revision: Union[str, None] = 'd29d02d9140b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modelos', sa.Column('categoria_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'modelos', 'categoria', ['categoria_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'modelos', type_='foreignkey')
    op.drop_column('modelos', 'categoria_id')
    # ### end Alembic commands ###
