"""BASE DE DATOS

Revision ID: a586e02bbbde
Revises: 
Create Date: 2025-05-26 10:43:45.585654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a586e02bbbde'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asesor',
    sa.Column('idAsesor', sa.Integer(), nullable=False),
    sa.Column('nombreAsesor', sa.String(length=60), nullable=True),
    sa.Column('apellidoAsesor', sa.String(length=60), nullable=True),
    sa.Column('correoAsesor', sa.String(length=60), nullable=True),
    sa.Column('telefonoAsesor', sa.Integer(), nullable=True),
    sa.Column('documentoAsesor', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('idAsesor')
    )
    op.create_table('categoria',
    sa.Column('idCategoria', sa.Integer(), nullable=False),
    sa.Column('estadoCategoria', sa.String(length=45), nullable=True),
    sa.Column('nombreCategoria', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('idCategoria')
    )
    op.create_table('mecanico',
    sa.Column('idMecanico', sa.Integer(), nullable=False),
    sa.Column('nombreMecanico', sa.String(length=60), nullable=True),
    sa.Column('apellidoMecanico', sa.String(length=60), nullable=True),
    sa.Column('correoMecanico', sa.String(length=60), nullable=True),
    sa.Column('telefonoMecanico', sa.Integer(), nullable=True),
    sa.Column('documentoMecanico', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('idMecanico')
    )
    op.create_table('rol',
    sa.Column('idRol', sa.Integer(), nullable=False),
    sa.Column('nombreRol', sa.String(length=60), nullable=True),
    sa.Column('estadoRol', sa.String(length=60), nullable=True),
    sa.Column('descripcionRol', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('idRol')
    )
    op.create_table('tipoAsesoria',
    sa.Column('idTipoAsesoria', sa.Integer(), nullable=False),
    sa.Column('nombreTipoAsesoria', sa.String(length=50), nullable=True),
    sa.Column('descripcionTipoAsesoria', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('idTipoAsesoria')
    )
    op.create_table('modelo',
    sa.Column('idModelo', sa.Integer(), nullable=False),
    sa.Column('referenciaModelo', sa.String(length=60), nullable=True),
    sa.Column('marcaModelo', sa.String(length=60), nullable=True),
    sa.Column('fechaLanzamientoModelo', sa.Date(), nullable=True),
    sa.Column('categoriaIdModelo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoriaIdModelo'], ['categoria.idCategoria'], ),
    sa.PrimaryKeyConstraint('idModelo')
    )
    op.create_table('usuario',
    sa.Column('idUsuario', sa.Integer(), nullable=False),
    sa.Column('nombreUsuario', sa.String(length=60), nullable=True),
    sa.Column('contraseñaUsuario', sa.String(length=60), nullable=True),
    sa.Column('telefonoUsuario', sa.Integer(), nullable=True),
    sa.Column('documentoUsuario', sa.Integer(), nullable=True),
    sa.Column('edadUsuario', sa.Integer(), nullable=True),
    sa.Column('correoUsuario', sa.String(length=60), nullable=True),
    sa.Column('rolIdUsuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rolIdUsuario'], ['rol.idRol'], ),
    sa.PrimaryKeyConstraint('idUsuario')
    )
    op.create_table('asesoria',
    sa.Column('idAsesoria', sa.Integer(), nullable=False),
    sa.Column('fechaSolicitudAsesoria', sa.Date(), nullable=True),
    sa.Column('estadoAsesoria', sa.String(length=50), nullable=True),
    sa.Column('necesidadAsesoria', sa.String(length=500), nullable=True),
    sa.Column('afinacionMayor', sa.String(length=400), nullable=True),
    sa.Column('mantenimientoCorrectivo', sa.String(length=400), nullable=True),
    sa.Column('mantenimientoPreventivo', sa.String(length=400), nullable=True),
    sa.Column('modificaciones', sa.String(length=400), nullable=True),
    sa.Column('usuarioIdAsesoria', sa.Integer(), nullable=True),
    sa.Column('asesorIdAsesoria', sa.Integer(), nullable=True),
    sa.Column('tipoAsesoriaIdAsesoria', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asesorIdAsesoria'], ['asesor.idAsesor'], ),
    sa.ForeignKeyConstraint(['tipoAsesoriaIdAsesoria'], ['tipoAsesoria.idTipoAsesoria'], ),
    sa.ForeignKeyConstraint(['usuarioIdAsesoria'], ['usuario.idUsuario'], ),
    sa.PrimaryKeyConstraint('idAsesoria')
    )
    op.create_table('vehiculo',
    sa.Column('idVehiculo', sa.Integer(), nullable=False),
    sa.Column('marcaVehiculo', sa.String(length=50), nullable=True),
    sa.Column('añoVehiculo', sa.Integer(), nullable=True),
    sa.Column('tipoVehiculo', sa.String(length=50), nullable=True),
    sa.Column('descripcionTecnicaVehiculo', sa.String(length=50), nullable=True),
    sa.Column('motor', sa.String(length=50), nullable=True),
    sa.Column('potencia', sa.String(length=50), nullable=True),
    sa.Column('Velocidad', sa.String(length=50), nullable=True),
    sa.Column('Transmision', sa.String(length=50), nullable=True),
    sa.Column('numerosCilindros', sa.String(length=50), nullable=True),
    sa.Column('cilindradas', sa.String(length=50), nullable=True),
    sa.Column('velocidadMaxima', sa.String(length=50), nullable=True),
    sa.Column('calibre', sa.String(length=50), nullable=True),
    sa.Column('potenciaMaxima', sa.String(length=50), nullable=True),
    sa.Column('modeloIdVehiculo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['modeloIdVehiculo'], ['modelo.idModelo'], ),
    sa.PrimaryKeyConstraint('idVehiculo')
    )
    op.create_table('accesorio',
    sa.Column('idAccesorio', sa.Integer(), nullable=False),
    sa.Column('nombreAccesorio', sa.String(length=100), nullable=True),
    sa.Column('descripcionAccesorio', sa.String(length=50), nullable=True),
    sa.Column('precioAccesorio', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('vehiculoIdAccesorio', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vehiculoIdAccesorio'], ['vehiculo.idVehiculo'], ),
    sa.PrimaryKeyConstraint('idAccesorio')
    )
    op.create_table('diagnosticos',
    sa.Column('idDiagnosticos', sa.Integer(), nullable=False),
    sa.Column('historialDiagnosticos', sa.String(length=60), nullable=True),
    sa.Column('diagnosticoVehiculo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['diagnosticoVehiculo'], ['vehiculo.idVehiculo'], ),
    sa.PrimaryKeyConstraint('idDiagnosticos')
    )
    op.create_table('galeriaVehiculoModificado',
    sa.Column('idGaleriaVehiculoModificado', sa.Integer(), nullable=False),
    sa.Column('nombreVehiculoGaleriaVehiculoModificado', sa.String(length=100), nullable=True),
    sa.Column('descripcionGaleriaVehiculoModificado', sa.String(length=100), nullable=True),
    sa.Column('usuarioIdGaleriaVehiculoModificado', sa.Integer(), nullable=True),
    sa.Column('vehiculoIdGaleriaVehiculoModificado', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuarioIdGaleriaVehiculoModificado'], ['usuario.idUsuario'], ),
    sa.ForeignKeyConstraint(['vehiculoIdGaleriaVehiculoModificado'], ['vehiculo.idVehiculo'], ),
    sa.PrimaryKeyConstraint('idGaleriaVehiculoModificado')
    )
    op.create_table('historialAsesoria',
    sa.Column('idHistorialAsesoria', sa.Integer(), nullable=False),
    sa.Column('comentariosHistorialAsesoria', sa.String(length=500), nullable=True),
    sa.Column('fechaRegistroHistorialAsesoria', sa.Date(), nullable=True),
    sa.Column('asesoriaIdHistorialAsesoria', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asesoriaIdHistorialAsesoria'], ['asesoria.idAsesoria'], ),
    sa.PrimaryKeyConstraint('idHistorialAsesoria')
    )
    op.create_table('servicio',
    sa.Column('idServicio', sa.Integer(), nullable=False),
    sa.Column('fechaSolicitudServicio', sa.Date(), nullable=True),
    sa.Column('estadoServicio', sa.String(length=50), nullable=True),
    sa.Column('necesidadServicio', sa.String(length=500), nullable=True),
    sa.Column('afinacionMayor', sa.String(length=400), nullable=True),
    sa.Column('mantenimientoCorrectivo', sa.String(length=400), nullable=True),
    sa.Column('mantenimientoPreventivo', sa.String(length=400), nullable=True),
    sa.Column('modificaciones', sa.String(length=400), nullable=True),
    sa.Column('asesoriaIdServicio', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asesoriaIdServicio'], ['asesoria.idAsesoria'], ),
    sa.PrimaryKeyConstraint('idServicio')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('servicio')
    op.drop_table('historialAsesoria')
    op.drop_table('galeriaVehiculoModificado')
    op.drop_table('diagnosticos')
    op.drop_table('accesorio')
    op.drop_table('vehiculo')
    op.drop_table('asesoria')
    op.drop_table('usuario')
    op.drop_table('modelo')
    op.drop_table('tipoAsesoria')
    op.drop_table('rol')
    op.drop_table('mecanico')
    op.drop_table('categoria')
    op.drop_table('asesor')
    # ### end Alembic commands ###
