"""Se suben las otras tablas

Revision ID: c9d613089cc4
Revises: 
Create Date: 2025-05-19 06:47:11.782996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9d613089cc4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asesor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombreAsesor', sa.String(length=60), nullable=True),
    sa.Column('apellidoAsesor', sa.String(length=60), nullable=True),
    sa.Column('correoAsesor', sa.String(length=60), nullable=True),
    sa.Column('telefonoAsesor', sa.Integer(), nullable=True),
    sa.Column('documentoAsesor', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asesoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fechaAsesoria', sa.Date(), nullable=True),
    sa.Column('horaAsesoria', sa.Date(), nullable=True),
    sa.Column('estadoAsesoria', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=45), nullable=True),
    sa.Column('nombre', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombreRol', sa.String(length=60), nullable=True),
    sa.Column('estadoRol', sa.String(length=60), nullable=True),
    sa.Column('descripcion', sa.String(length=60), nullable=True),
    sa.Column('correo', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=60), nullable=True),
    sa.Column('estadoServicio', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=True),
    sa.Column('contraseña', sa.String(length=60), nullable=True),
    sa.Column('telefono', sa.Integer(), nullable=True),
    sa.Column('documento', sa.Integer(), nullable=True),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('correo', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modelos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referencia', sa.String(length=60), nullable=True),
    sa.Column('marca', sa.String(length=60), nullable=True),
    sa.Column('fechaLanzamiento', sa.Date(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('modelos')
    op.drop_table('usuario')
    op.drop_table('servicio')
    op.drop_table('rol')
    op.drop_table('categoria')
    op.drop_table('asesoria')
    op.drop_table('asesor')
    # ### end Alembic commands ###
