"""creada tabla de modelos

Revision ID: d29d02d9140b
Revises: 
Create Date: 2025-05-16 11:08:42.567001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd29d02d9140b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=45), nullable=True),
    sa.Column('nombre', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modelos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referencia', sa.String(length=60), nullable=True),
    sa.Column('marca', sa.String(length=60), nullable=True),
    sa.Column('fechaLanzamiento', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('modelos')
    op.drop_table('categoria')
    # ### end Alembic commands ###
