"""Se suben todas las tablas centradas en asesorias y otras tablas de relleno

Revision ID: ef991e56663b
Revises: c9d613089cc4
Create Date: 2025-05-26 01:02:51.580913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ef991e56663b'
down_revision: Union[str, None] = 'c9d613089cc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marca',
    sa.Column('idMarca', sa.Integer(), nullable=False),
    sa.Column('nombreMarca', sa.String(length=50), nullable=True),
    sa.Column('paisOrigenMarca', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('idMarca')
    )
    op.create_table('tiposAsesoria',
    sa.Column('idTipoAsesoria', sa.Integer(), nullable=False),
    sa.Column('nombreTipoTipoAsesoria', sa.String(length=50), nullable=True),
    sa.Column('descripcionTipoAsesoria', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('idTipoAsesoria')
    )
    op.create_table('modelo',
    sa.Column('idModelo', sa.Integer(), nullable=False),
    sa.Column('referenciaModelo', sa.String(length=60), nullable=True),
    sa.Column('marcaModelo', sa.String(length=60), nullable=True),
    sa.Column('fechaLanzamientoModelo', sa.Date(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.idCategoria'], ),
    sa.PrimaryKeyConstraint('idModelo')
    )
    op.create_table('blogExperiencia',
    sa.Column('idBlog', sa.Integer(), nullable=False),
    sa.Column('fechaPublicidadBlog', sa.String(length=500), nullable=True),
    sa.Column('idUsuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idUsuario'], ['usuario.idUsuario'], ),
    sa.PrimaryKeyConstraint('idBlog')
    )
    op.create_table('vehiculo',
    sa.Column('idVehiculo', sa.Integer(), nullable=False),
    sa.Column('marcaVehiculo', sa.String(length=50), nullable=True),
    sa.Column('modeloVehiculo', sa.String(length=50), nullable=True),
    sa.Column('añoVehiculo', sa.Integer(), nullable=True),
    sa.Column('tipoVehiculo', sa.String(length=50), nullable=True),
    sa.Column('descripcionTecnicaVehiculo', sa.String(length=50), nullable=True),
    sa.Column('idModelo3D', sa.Integer(), nullable=True),
    sa.Column('marca_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idModelo3D'], ['modelo.idModelo'], ),
    sa.ForeignKeyConstraint(['marca_id'], ['marca.idMarca'], ),
    sa.PrimaryKeyConstraint('idVehiculo')
    )
    op.create_table('accesorio',
    sa.Column('idAccesorio', sa.Integer(), nullable=False),
    sa.Column('nombreAccesorio', sa.String(length=100), nullable=True),
    sa.Column('descripcionAccesorio', sa.String(length=50), nullable=True),
    sa.Column('precioAccesorio', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('idVehiculo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idVehiculo'], ['vehiculo.idVehiculo'], ),
    sa.PrimaryKeyConstraint('idAccesorio')
    )
    op.create_table('galeriaVehiculoModificado',
    sa.Column('idGaleria', sa.Integer(), nullable=False),
    sa.Column('nombreVehiculoGaleria', sa.String(length=100), nullable=True),
    sa.Column('descripcionGaleria', sa.String(length=100), nullable=True),
    sa.Column('idUsuario', sa.Integer(), nullable=True),
    sa.Column('idVehiculo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idUsuario'], ['usuario.idUsuario'], ),
    sa.ForeignKeyConstraint(['idVehiculo'], ['vehiculo.idVehiculo'], ),
    sa.PrimaryKeyConstraint('idGaleria')
    )
    op.create_table('historialAsesoria',
    sa.Column('idHistorial', sa.Integer(), nullable=False),
    sa.Column('comentariosHistorial', sa.String(length=500), nullable=True),
    sa.Column('fechaRegistroHistorial', sa.Date(), nullable=True),
    sa.Column('idAsesoria', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idAsesoria'], ['asesoria.idAsesoria'], ),
    sa.PrimaryKeyConstraint('idHistorial')
    )
    op.drop_table('modelos')
    op.add_column('asesor', sa.Column('idAsesor', sa.Integer(), nullable=False))
    op.drop_column('asesor', 'id')
    op.add_column('asesoria', sa.Column('idAsesoria', sa.Integer(), nullable=False))
    op.add_column('asesoria', sa.Column('fechaSolicitudAsesoria', sa.Date(), nullable=True))
    op.add_column('asesoria', sa.Column('necesidadAsesoria', sa.String(length=500), nullable=True))
    op.add_column('asesoria', sa.Column('idUsuario', sa.Integer(), nullable=True))
    op.add_column('asesoria', sa.Column('idAsesor', sa.Integer(), nullable=True))
    op.add_column('asesoria', sa.Column('idTipoAsesoria', sa.Integer(), nullable=True))
    op.alter_column('asesoria', 'estadoAsesoria',
               existing_type=mysql.VARCHAR(length=60),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.create_foreign_key(None, 'asesoria', 'asesor', ['idAsesor'], ['idAsesor'])
    op.create_foreign_key(None, 'asesoria', 'usuario', ['idUsuario'], ['idUsuario'])
    op.create_foreign_key(None, 'asesoria', 'tiposAsesoria', ['idTipoAsesoria'], ['idTipoAsesoria'])
    op.drop_column('asesoria', 'horaAsesoria')
    op.drop_column('asesoria', 'id')
    op.drop_column('asesoria', 'fechaAsesoria')
    op.add_column('categoria', sa.Column('idCategoria', sa.Integer(), nullable=False))
    op.add_column('categoria', sa.Column('estadoCategoria', sa.String(length=45), nullable=True))
    op.add_column('categoria', sa.Column('nombreCategoria', sa.String(length=60), nullable=True))
    op.drop_column('categoria', 'nombre')
    op.drop_column('categoria', 'estado')
    op.drop_column('categoria', 'id')
    op.add_column('rol', sa.Column('idRol', sa.Integer(), nullable=False))
    op.add_column('rol', sa.Column('descripcionRol', sa.String(length=60), nullable=True))
    op.drop_column('rol', 'descripcion')
    op.drop_column('rol', 'correo')
    op.drop_column('rol', 'id')
    op.add_column('servicio', sa.Column('idServicio', sa.Integer(), nullable=False))
    op.add_column('servicio', sa.Column('descripcionServicio', sa.String(length=60), nullable=True))
    op.add_column('servicio', sa.Column('idAsesoria', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'servicio', 'asesoria', ['idAsesoria'], ['idAsesoria'])
    op.drop_column('servicio', 'descripcion')
    op.drop_column('servicio', 'id')
    op.add_column('usuario', sa.Column('idUsuario', sa.Integer(), nullable=False))
    op.add_column('usuario', sa.Column('nombreUsuario', sa.String(length=60), nullable=True))
    op.add_column('usuario', sa.Column('contraseñaUsuario', sa.String(length=60), nullable=True))
    op.add_column('usuario', sa.Column('telefonoUsuario', sa.Integer(), nullable=True))
    op.add_column('usuario', sa.Column('documentoUsuario', sa.Integer(), nullable=True))
    op.add_column('usuario', sa.Column('edadUsuario', sa.Integer(), nullable=True))
    op.add_column('usuario', sa.Column('correoUsuario', sa.String(length=60), nullable=True))
    op.add_column('usuario', sa.Column('rol_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'usuario', 'rol', ['rol_id'], ['idRol'])
    op.drop_column('usuario', 'nombre')
    op.drop_column('usuario', 'correo')
    op.drop_column('usuario', 'documento')
    op.drop_column('usuario', 'telefono')
    op.drop_column('usuario', 'edad')
    op.drop_column('usuario', 'contraseña')
    op.drop_column('usuario', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.add_column('usuario', sa.Column('contraseña', mysql.VARCHAR(length=60), nullable=True))
    op.add_column('usuario', sa.Column('edad', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('usuario', sa.Column('telefono', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('usuario', sa.Column('documento', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('usuario', sa.Column('correo', mysql.VARCHAR(length=60), nullable=True))
    op.add_column('usuario', sa.Column('nombre', mysql.VARCHAR(length=60), nullable=True))
    op.drop_constraint(None, 'usuario', type_='foreignkey')
    op.drop_column('usuario', 'rol_id')
    op.drop_column('usuario', 'correoUsuario')
    op.drop_column('usuario', 'edadUsuario')
    op.drop_column('usuario', 'documentoUsuario')
    op.drop_column('usuario', 'telefonoUsuario')
    op.drop_column('usuario', 'contraseñaUsuario')
    op.drop_column('usuario', 'nombreUsuario')
    op.drop_column('usuario', 'idUsuario')
    op.add_column('servicio', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.add_column('servicio', sa.Column('descripcion', mysql.VARCHAR(length=60), nullable=True))
    op.drop_constraint(None, 'servicio', type_='foreignkey')
    op.drop_column('servicio', 'idAsesoria')
    op.drop_column('servicio', 'descripcionServicio')
    op.drop_column('servicio', 'idServicio')
    op.add_column('rol', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.add_column('rol', sa.Column('correo', mysql.VARCHAR(length=60), nullable=True))
    op.add_column('rol', sa.Column('descripcion', mysql.VARCHAR(length=60), nullable=True))
    op.drop_column('rol', 'descripcionRol')
    op.drop_column('rol', 'idRol')
    op.add_column('categoria', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.add_column('categoria', sa.Column('estado', mysql.VARCHAR(length=45), nullable=True))
    op.add_column('categoria', sa.Column('nombre', mysql.VARCHAR(length=60), nullable=True))
    op.drop_column('categoria', 'nombreCategoria')
    op.drop_column('categoria', 'estadoCategoria')
    op.drop_column('categoria', 'idCategoria')
    op.add_column('asesoria', sa.Column('fechaAsesoria', sa.DATE(), nullable=True))
    op.add_column('asesoria', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.add_column('asesoria', sa.Column('horaAsesoria', sa.DATE(), nullable=True))
    op.drop_constraint(None, 'asesoria', type_='foreignkey')
    op.drop_constraint(None, 'asesoria', type_='foreignkey')
    op.drop_constraint(None, 'asesoria', type_='foreignkey')
    op.alter_column('asesoria', 'estadoAsesoria',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=60),
               existing_nullable=True)
    op.drop_column('asesoria', 'idTipoAsesoria')
    op.drop_column('asesoria', 'idAsesor')
    op.drop_column('asesoria', 'idUsuario')
    op.drop_column('asesoria', 'necesidadAsesoria')
    op.drop_column('asesoria', 'fechaSolicitudAsesoria')
    op.drop_column('asesoria', 'idAsesoria')
    op.add_column('asesor', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.drop_column('asesor', 'idAsesor')
    op.create_table('modelos',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('referencia', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('marca', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('fechaLanzamiento', sa.DATE(), nullable=True),
    sa.Column('categoria_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], name=op.f('modelos_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('historialAsesoria')
    op.drop_table('galeriaVehiculoModificado')
    op.drop_table('accesorio')
    op.drop_table('vehiculo')
    op.drop_table('blogExperiencia')
    op.drop_table('modelo')
    op.drop_table('tiposAsesoria')
    op.drop_table('marca')
    # ### end Alembic commands ###
